#config
application:
 musicPath: C:\\Music\\
 
#to run via spring boot on docker containers
#spring:
# datasource: 
#  url: jdbc:mysql://192.168.0.21:3307/ARTIST_AND_ALBUMS

#run via eclipse local host
spring:
 kafka:
  bootstrap-servers: localhost:9092
  consumer:
   group-id: my-group-id
 datasource:
  url: jdbc:mysql://localhost:3306/ARTIST_AND_ALBUMS
  username: root
  password: password
  driver-class-name: com.mysql.cj.jdbc.Driver
 jpa:
  show-sql: true
  hibernate:
   ddl-auto: update
  database-platform: org.hibernate.dialect.MySQL8Dialect
#  properties:
#   hibernate:
#    session:
#     events:
#      log:
#       LOG_QUERIES_SLOWER_THAN_MS: 1
#    generate_statistics: true
#    stat_category: DEBUG
#    jdbc.batch_size: 50
#    order_inserts: true
springdoc:
 swagger-ui:
  path: /swagger-ui/index.html
  operationsSorter: method
 api-docs:
  enabled: true
logging:
 file:
  name: ./logs/artist-and-albums.log
 level:
  root: INFO
 pattern:
  console: '[%d{yy-MM-dd HH:mm:ss:SSS}][%-5p][%c][%t]%m%n'
  file: '[%d{yy-MM-dd HH:mm:ss:SSS}][%-5p][%c][%t]%m%n'
 logback:
  rollingpolicy:
   max-history: 15
   max-file-size: 10MB
   file-name-pattern: '${LOG_FILE}.%d{yyyy-MM-dd}.%i'