#config
application:
 musicPath: F:\\Music\\

spring:
 kafka:
  consumer:
   auto-offset-reset: earliest
   bootstrap-servers: 192.168.0.21:29092                   # Must use IP address not localhost when deploying app to docker
   group-id: my-group-id
   key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
   value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
  producer:
   acks: -1
   bootstrap-servers: 192.168.0.21:29092                    # Must use IP address not localhost when deploying app to docker
   key-serializer: org.apache.kafka.common.serialization.StringSerializer
   value-serializer: org.springframework.kafka.support.serializer.JsonSerializer 
 datasource:
  url: jdbc:mysql://192.168.0.21:3307/artist_and_albums      # Must use IP address not localhost when deploying app to docker
  #url: jdbc:mysql://localhost:3307/artist_and_albums        # Use localhost when running application via eclipse
  username: root
  password: password
  driver-class-name: com.mysql.cj.jdbc.Driver
 jpa:
  show-sql: true
  hibernate:
   ddl-auto: update
  database-platform: org.hibernate.dialect.MySQL8Dialect
springdoc:
 swagger-ui:
  path: /swagger-ui/index.html
  operationsSorter: method
 api-docs:
  enabled: true
logging:
 file:
  name: ./logs/artist-and-albums.log
 level:
  root: INFO
 pattern:
  console: '[%d{yy-MM-dd HH:mm:ss:SSS}][%-5p][%c][%t]%m%n'
  file: '[%d{yy-MM-dd HH:mm:ss:SSS}][%-5p][%c][%t]%m%n'
 logback:
  rollingpolicy:
   max-history: 15
   max-file-size: 10MB
   file-name-pattern: '${LOG_FILE}.%d{yyyy-MM-dd}.%i'